In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray (n-dimensional array)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
            
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a4 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]],
               [[19, 20, 21],
                [22, 23, 24],
                [25, 26, 27]]])

In [8]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a4.shape

(3, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 2, 3, 3)

In [14]:
a5 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]],
               [[17, 18, 19, 20],
                [21, 22, 23, 24],
                [25, 26, 27, 28],
                [29, 30, 31, 32]]])

In [15]:
a5

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [16]:
a5.ndim

3

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [21]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [23]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array_1 = np.random.randint(0, 10, size=(3, 5))
random_array_1

array([[6, 3, 0, 5, 9],
       [9, 6, 3, 6, 2],
       [9, 8, 6, 3, 0]])

In [29]:
random_array_1.size

15

In [30]:
random_array_1.shape

(3, 5)

In [31]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.47377104, 0.06595187, 0.60895653],
       [0.43221407, 0.5664022 , 0.22737949],
       [0.06733573, 0.4808151 , 0.39081364],
       [0.89018815, 0.0135124 , 0.79122994],
       [0.19476935, 0.37782109, 0.99324875]])

In [32]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.31251637, 0.68622435, 0.5490657 ],
       [0.96153244, 0.50889142, 0.11868   ],
       [0.08092028, 0.58742364, 0.06728133],
       [0.62658373, 0.75476224, 0.6946837 ],
       [0.92593284, 0.448343  , 0.97012623]])

In [37]:
# Pseudo-random numbers
np.random.seed(seed=0)
# seed can be any number
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
random_array_4.shape

(5, 3)

In [40]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays & Matrices

In [41]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1

array([1, 2, 3])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a1[0]

1

In [47]:
a2.shape

(2, 3)

In [46]:
a2[0]

array([1. , 2. , 3.3])

In [48]:
a3.shape

(2, 3, 3)

In [49]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
a3[:2, :3, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [56]:
a6 = np.random.randint(10, size=(2, 3, 4, 5))
a6

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [57]:
a6.shape, a6.ndim

((2, 3, 4, 5), 4)

In [60]:
a6[1, 1, 0, :4]

array([9, 9, 0, 6])

In [62]:
a6[:, :, :, :3]

array([[[[3, 5, 8],
         [5, 0, 0],
         [9, 6, 4],
         [3, 3, 8]],

        [[1, 0, 0],
         [7, 9, 3],
         [7, 7, 0],
         [3, 1, 3]],

        [[4, 3, 1],
         [9, 1, 2],
         [2, 5, 7],
         [9, 9, 3]]],


       [[[3, 0, 4],
         [7, 2, 7],
         [6, 6, 5],
         [7, 1, 5]],

        [[9, 9, 0],
         [6, 8, 2],
         [6, 1, 5],
         [9, 8, 6]],

        [[7, 5, 4],
         [8, 1, 5],
         [3, 7, 7],
         [7, 5, 9]]]])

## 4. Manipulating & Comparing Arrays

### Arithmetic

In [63]:
a1

array([1, 2, 3])

In [64]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [65]:
a1 + ones

array([2., 3., 4.])

In [66]:
a1 - ones

array([0., 1., 2.])

In [67]:
a1 * ones

array([1., 2., 3.])

In [68]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [69]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [71]:
# Numpy Broadcasting
# a2 * a3 => ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)
# How can we reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array?"

In [72]:
a1 / ones

array([1., 2., 3.])

In [74]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [73]:
# Floor division => Removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [75]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [76]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [77]:
np.add(a1, ones)

array([2., 3., 4.])

In [78]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [79]:
np.mod(a1, 2)

array([1, 0, 1], dtype=int32)

In [80]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [81]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [82]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
# 8 videos done